### ISSUE TITLE
0.1.4 broke in ember-cli 2.14.2

### ISSUE THREAD

**Issue by scottmessinger** [kaliber5/ember-sticky-element#14]
In my package.json, I had `"ember-sticky-element": "^0.1.3"`. When I deployed it, I wasn't using a shrinkwrapped json file or yarn and the deploy process used ember-sticky-element `0.1.4`. My app then broken with the error: `Error sticky-element not found, and the catch-all block handler...`. After I fixed the version to `0.1.3`, things worked again.

Not sure what's going on, but it seems something about the change from 0.1.3 to 0.1.4 caused things to break.  Sorry I don't have anything more concrete!

**Comment by scottmessinger** [comment]
Oh, by the way, I really appreciate this addon! It's been great and I'm grateful you released i!

**Comment by simonihmig** [comment]
Hm, seems to be a duplicate of #13. But good to have this confirmed, will look at it asap!

> Oh, by the way, I really appreciate this addon! It's been great and I'm grateful you released i!

Thank you! :)

**Comment by simonihmig** [comment]
Fixed, see #13
