### ISSUE TITLE
Sticky only if parent is of a minimum height

### ISSUE THREAD

**Issue by knownasilya** [kaliber5/ember-sticky-element#4]
Sometimes the parent container is so small that making the header sticky just doesn't make sense. Would love an option to set a minimum parent height before sticky enables.

**Comment by knownasilya** [comment]
Ping @simonihmig

**Comment by simonihmig** [comment]
@knownasilya thanks for pinging, sorry I somehow missed that!

The parent height logic seems quite tailored to this specific use case. What about we make this more generic, like just having an `enabled` property? The user could then implement his own logic for when to enable or disable.

I guess you are asking for this component here, right? https://github.com/ember-learn/ember-api-docs/pull/336/files#diff-34fdee68b53d5293a6d632b6a8d79636
I guess it could easily measure its own height, and implement something like `stickyEnabled: gt('ownHeight', 100)` to pipe that into the sticky element's `enabled` property.

Does that make sense?

**Comment by knownasilya** [comment]
Perfect 👍
